name: kybers_flutter
description: Flutter IPTV application with HLS/M3U8 support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Video player for HLS/M3U8 streams
  video_player: ^2.8.1
  
  # HTTP requests for APIs
  http: ^1.1.0
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Cached network images
  cached_network_image: ^3.3.0
  
  # Material icons
  cupertino_icons: ^1.0.2
  
  # Persistent storage for user profiles and cache
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Testing dependencies
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - .env